export interface MomentumAsset {
  rank: number;
  ticker: string;
  name: string;
  type: "stock" | "crypto";
  price: number;
  change24h: number;
  momentumScore: number;
  status: "hot" | "fading" | "neutral";
  volume: string;
  rsi: number;
  macdSignal: "bullish" | "bearish" | "neutral";
  bollingerPosition: "upper" | "middle" | "lower";
}

export const momentumAssets: MomentumAsset[] = [
  {
    rank: 1,
    ticker: "NVDA",
    name: "NVIDIA Corp",
    type: "stock",
    price: 924.79,
    change24h: 4.82,
    momentumScore: 94,
    status: "hot",
    volume: "52.3M",
    rsi: 72,
    macdSignal: "bullish",
    bollingerPosition: "upper",
  },
  {
    rank: 2,
    ticker: "BTC",
    name: "Bitcoin",
    type: "crypto",
    price: 67842.5,
    change24h: 3.21,
    momentumScore: 91,
    status: "hot",
    volume: "28.4B",
    rsi: 68,
    macdSignal: "bullish",
    bollingerPosition: "upper",
  },
  {
    rank: 3,
    ticker: "TSLA",
    name: "Tesla Inc",
    type: "stock",
    price: 248.23,
    change24h: 2.94,
    momentumScore: 88,
    status: "hot",
    volume: "89.1M",
    rsi: 65,
    macdSignal: "bullish",
    bollingerPosition: "upper",
  },
  {
    rank: 4,
    ticker: "ETH",
    name: "Ethereum",
    type: "crypto",
    price: 3521.87,
    change24h: 2.15,
    momentumScore: 85,
    status: "hot",
    volume: "14.2B",
    rsi: 62,
    macdSignal: "bullish",
    bollingerPosition: "middle",
  },
  {
    rank: 5,
    ticker: "AAPL",
    name: "Apple Inc",
    type: "stock",
    price: 189.84,
    change24h: 1.23,
    momentumScore: 78,
    status: "neutral",
    volume: "48.7M",
    rsi: 55,
    macdSignal: "neutral",
    bollingerPosition: "middle",
  },
  {
    rank: 6,
    ticker: "SOL",
    name: "Solana",
    type: "crypto",
    price: 172.45,
    change24h: 5.67,
    momentumScore: 87,
    status: "hot",
    volume: "3.2B",
    rsi: 71,
    macdSignal: "bullish",
    bollingerPosition: "upper",
  },
  {
    rank: 7,
    ticker: "AMD",
    name: "AMD Inc",
    type: "stock",
    price: 164.32,
    change24h: 3.12,
    momentumScore: 82,
    status: "hot",
    volume: "42.1M",
    rsi: 64,
    macdSignal: "bullish",
    bollingerPosition: "middle",
  },
  {
    rank: 8,
    ticker: "MSFT",
    name: "Microsoft",
    type: "stock",
    price: 425.22,
    change24h: 0.87,
    momentumScore: 72,
    status: "neutral",
    volume: "18.3M",
    rsi: 52,
    macdSignal: "neutral",
    bollingerPosition: "middle",
  },
  {
    rank: 9,
    ticker: "DOGE",
    name: "Dogecoin",
    type: "crypto",
    price: 0.1542,
    change24h: -2.34,
    momentumScore: 45,
    status: "fading",
    volume: "1.8B",
    rsi: 38,
    macdSignal: "bearish",
    bollingerPosition: "lower",
  },
  {
    rank: 10,
    ticker: "META",
    name: "Meta Platforms",
    type: "stock",
    price: 505.95,
    change24h: 1.56,
    momentumScore: 76,
    status: "neutral",
    volume: "12.4M",
    rsi: 58,
    macdSignal: "bullish",
    bollingerPosition: "middle",
  },
  {
    rank: 11,
    ticker: "XRP",
    name: "Ripple",
    type: "crypto",
    price: 0.5234,
    change24h: -1.82,
    momentumScore: 42,
    status: "fading",
    volume: "2.1B",
    rsi: 35,
    macdSignal: "bearish",
    bollingerPosition: "lower",
  },
  {
    rank: 12,
    ticker: "GOOGL",
    name: "Alphabet Inc",
    type: "stock",
    price: 175.98,
    change24h: 0.92,
    momentumScore: 68,
    status: "neutral",
    volume: "21.5M",
    rsi: 51,
    macdSignal: "neutral",
    bollingerPosition: "middle",
  },
  {
    rank: 13,
    ticker: "AVAX",
    name: "Avalanche",
    type: "crypto",
    price: 38.72,
    change24h: 4.23,
    momentumScore: 79,
    status: "hot",
    volume: "842M",
    rsi: 66,
    macdSignal: "bullish",
    bollingerPosition: "upper",
  },
  {
    rank: 14,
    ticker: "INTC",
    name: "Intel Corp",
    type: "stock",
    price: 31.24,
    change24h: -3.45,
    momentumScore: 28,
    status: "fading",
    volume: "38.9M",
    rsi: 29,
    macdSignal: "bearish",
    bollingerPosition: "lower",
  },
];

export const allTickers = [
  { ticker: "NVDA", name: "NVIDIA Corp" },
  { ticker: "BTC", name: "Bitcoin" },
  { ticker: "TSLA", name: "Tesla Inc" },
  { ticker: "ETH", name: "Ethereum" },
  { ticker: "AAPL", name: "Apple Inc" },
  { ticker: "SOL", name: "Solana" },
  { ticker: "AMD", name: "AMD Inc" },
  { ticker: "MSFT", name: "Microsoft" },
  { ticker: "DOGE", name: "Dogecoin" },
  { ticker: "META", name: "Meta Platforms" },
  { ticker: "XRP", name: "Ripple" },
  { ticker: "GOOGL", name: "Alphabet Inc" },
  { ticker: "AVAX", name: "Avalanche" },
  { ticker: "INTC", name: "Intel Corp" },
  { ticker: "AMZN", name: "Amazon" },
  { ticker: "NFLX", name: "Netflix" },
  { ticker: "LINK", name: "Chainlink" },
  { ticker: "ADA", name: "Cardano" },
  { ticker: "MATIC", name: "Polygon" },
  { ticker: "CRM", name: "Salesforce" },
];
